Add vehicle engine type information
Cnam-MobiPark/MobiPark pull request #10
Opened 2024-05-26 15:42 UTC by bastianfbr

2024-05-29 16:07 UTC, Bricklou requested changes

2024-05-29 16:07 UTC, Bricklou commented on backend/MobiPark.Domain.Test/EngineTest.cs
> +    }
Test inutile?

2024-05-29 16:07 UTC, Bricklou commented on backend/MobiPark.Domain.Test/EngineTest.cs
> +        Assert.IsType<ElectricalEngine>(engine);
Pas de vérification de valeurs invalides ? (inférieur à 0)

2024-05-29 16:07 UTC, Bricklou commented on backend/MobiPark.Domain/Models/Vehicle/Engine/ElectricalEngine.cs
> +            this.currentBatteryCapacity = currentBatteryCapacity;
Vérification de valeurs aberrantes ?

2024-05-29 16:07 UTC, Bricklou commented on backend/MobiPark.Domain/Models/Vehicle/Engine/Engine.cs
> +public class Engine
abstract class

2024-05-29 16:07 UTC, Bricklou commented on backend/MobiPark.Domain/Services/VehicleService.cs
>          }
supprime, on ne doit plus s'en servir

2024-05-29 17:00 UTC, bastianfbr commented on backend/MobiPark.Domain.Test/EngineTest.cs
> +    }
Sorry ✅

2024-05-29 20:23 UTC, bastianfbr commented on backend/MobiPark.Domain/Models/Vehicle/Engine/ElectricalEngine.cs
> +            this.currentBatteryCapacity = currentBatteryCapacity;
Fait

2024-05-29 20:23 UTC, bastianfbr commented on backend/MobiPark.Domain.Test/EngineTest.cs
> +        Assert.IsType<ElectricalEngine>(engine);
Fait aussi

2024-05-29 20:26 UTC, bastianfbr commented on backend/MobiPark.Domain/Models/Vehicle/Engine/Engine.cs
> +public class Engine
Fait

2024-05-29 20:49 UTC, bastianfbr commented on backend/MobiPark.Domain/Services/VehicleService.cs
>          }
fait

2024-05-30 16:23 UTC, Bricklou approved these changes

2024-05-30 16:38 UTC, merged